version: v3
services:
  postgres-db:
    image: postgres:16beta2-alpine3.18
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    
      
  api:
    depends_on:
      - postgres-db
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://admin:admin@postgres-db:5432/simple_bank?sslmode=disable
